n = int(input('Digite um número para ver sua tabuada: '))
print('{} X  1 = {}\n{} X  2 = {}\n{} X  3 = {}\n{} X  4 = {}\n{} X  5 = {}\n{} X  6 = {}\n{} X  7 = {}\n{} X  8 = {}\n{} X  9 = {}\n{} X 10 = {}'.format(n, (n*1), n, (n*2), n, (n*3), n, (n*4), n, (n*5), n, (n*6), n, (n*7), n, (n*8), n, (n*9), n, (n*10)))
# ou fazendo em linha por linha
print('=' * 11)
print('{} X {:2} = {}'.format(n, 0, n*0))
print('{} X {:2} = {}'.format(n, 1, n*1))
print('{} X {:2} = {}'.format(n, 2, n*2))
print('{} X {:2} = {}'.format(n, 3, n*3))
print('{} X {:2} = {}'.format(n, 4, n*4))
print('{} X {:2} = {}'.format(n, 5, n*5))
print('{} X {:2} = {}'.format(n, 6, n*6))
print('{} X {:2} = {}'.format(n, 7, n*7))
print('{} X {:2} = {}'.format(n, 8, n*8))
print('{} X {:2} = {}'.format(n, 9, n*9))
print('{} X {:2} = {}'.format(n, 10, n*10))
print('=' * 11)