a = input('Digite algo: ')
print('O tipo primitivo desta entrada é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Esta somente em maiúsculas?', a.isupper())
print('Esta somente em minúsculas?', a.islower())
print('Esta capitalizada?', a.istitle())
